# Generated by Django 2.0.6 on 2018-06-28 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_email', models.CharField(max_length=40, unique=True)),
                ('account_pw', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Favor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='favor',
            name='menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Menu'),
        ),
        migrations.AlterUniqueTogether(
            name='favor',
            unique_together={('account_id', 'menu_id')},
        ),
    ]
